// SPDX-License-Identifier: LGPL-2.1-or-later
//
// PORT-SYNC: src/shared/generator.c, src/shared/generator.h
//
// Generator utility functions for creating unit files, symlinks,
// and drop-in configuration for systemd generators.

use std::fmt;
use std::sync::OnceLock;

// ── Error type ──────────────────────────────────────────────────────────

/// Errors returned by generator utility functions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GeneratorError {
    /// A required argument was empty or missing.
    InvalidArgument,
    /// Expected a regular file path but received a directory path.
    IsDirectory,
    /// The requested operation is not supported.
    NotSupported,
}

impl fmt::Display for GeneratorError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidArgument => write!(f, "invalid argument"),
            Self::IsDirectory => write!(f, "path refers to a directory, not a file"),
            Self::NotSupported => write!(f, "operation not supported"),
        }
    }
}

impl std::error::Error for GeneratorError {}

// ── Enums ───────────────────────────────────────────────────────────────

/// GPT auto-root partition detection mode.
///
/// Controls how partition auto-detection is configured via the kernel
/// command line `root=` parameter.  Mirrors the C `GptAutoRoot` enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GptAutoRoot {
    /// Auto-detection disabled (default / unknown values).
    Off,
    /// Auto-detection enabled, respecting factory-reset mode.
    On,
    /// Auto-detection forced, ignoring factory-reset mode.
    Force,
    /// Full-image dissection, respecting factory-reset mode.
    Dissect,
    /// Full-image dissection forced, ignoring factory-reset mode.
    DissectForce,
}

// ── Private helpers ─────────────────────────────────────────────────────

fn specifier_escape(s: &str) -> String {
    s.replace('%', "%%")
}

fn cescape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\x00"),
            c if c.is_control() => {
                out.push_str(&format!("\\x{:02x}", ch as u32));
            }
            c => out.push(c),
        }
    }
    out
}

// Mirrors systemd's `empty_to_dash`.
fn empty_to_dash(s: Option<&str>) -> &str {
    match s {
        Some(v) if !v.is_empty() => v,
        _ => "-",
    }
}

// Mirrors systemd's `strempty`.
fn strempty<'a>(s: Option<&'a str>) -> &'a str {
    s.unwrap_or("")
}

// Mirrors `unit_name_path_escape` for the common generator cases.
fn unit_name_path_escape(path: &str) -> String {
    let trimmed = path.trim_matches('/');
    if trimmed.is_empty() {
        return String::new();
    }
    let mut result = String::with_capacity(trimmed.len());
    for ch in trimmed.chars() {
        match ch {
            '/' => result.push('-'),
            '\\' => result.push_str("\\x5c"),
            '\0'..='\x1f' => result.push_str(&format!("\\x{:02x}", ch as u32)),
            _ => result.push(ch),
        }
    }
    result.trim_matches('-').to_string()
}

// ── Public API ──────────────────────────────────────────────────────────

/// Generate the standard auto-generated header comment for unit files.
///
/// # Examples
///
/// ```
/// assert!(generator_header("systemd-fstab-generator").starts_with("# Automatically generated by"));
/// ```
pub fn generator_header(program: &str) -> String {
    format!("# Automatically generated by {program}\n\n")
}

/// Parse the GPT auto-root detection mode from a kernel command line value.
///
/// Mirrors the C `parse_gpt_auto_root()`.  Returns [`GptAutoRoot::Off`]
/// for the value `"off"` and for any unrecognised value.
///
/// # Panics
///
/// Panics if `switch_name` or `value` is empty.
pub fn parse_gpt_auto_root(switch_name: &str, value: &str) -> GptAutoRoot {
    assert!(!switch_name.is_empty(), "switch_name must not be empty");
    assert!(!value.is_empty(), "value must not be empty");

    match value {
        "gpt-auto" => GptAutoRoot::On,
        "gpt-auto-force" => GptAutoRoot::Force,
        "dissect" => GptAutoRoot::Dissect,
        "dissect-force" => GptAutoRoot::DissectForce,
        _ => GptAutoRoot::Off,
    }
}

/// Parse the `SYSTEMD_SOFT_REBOOTS_COUNT` value and return whether the
/// system has been soft-rebooted (count > 0).
///
/// This is the pure-logic core extracted from [`generator_soft_rebooted`]
/// so it can be tested without touching the process environment.
pub fn soft_rebooted_from_value(raw: Option<&str>) -> bool {
    raw.and_then(|v| v.parse::<u32>().ok())
        .map(|n| n > 0)
        .unwrap_or(false)
}

/// Check whether the system has been soft-rebooted.
///
/// Reads `SYSTEMD_SOFT_REBOOTS_COUNT` from the environment and returns
/// `true` when the value is present and greater than zero.
/// The result is cached for the process lifetime.
pub fn generator_soft_rebooted() -> bool {
    static CACHE: OnceLock<bool> = OnceLock::new();
    *CACHE.get_or_init(|| {
        soft_rebooted_from_value(std::env::var("SYSTEMD_SOFT_REBOOTS_COUNT").ok().as_deref())
    })
}

/// Compute the `(from, to)` paths for a generator dependency symlink.
///
/// * `dep_type` = `Some("wants")`  → creates a `<dst>.wants/<src>` dependency
/// * `dep_type` = `None`           → creates an alias symlink to `<src>`
/// * `instance` = `Some("sda1")`   → instantiate template `<src>` → `<src>@sda1.<suffix>`
///
/// # Errors
///
/// Returns [`GeneratorError::InvalidArgument`] if `dir`, `dst`, or `src` is empty.
/// Returns [`GeneratorError::IsDirectory`] if `src` ends with `/`.
pub fn generator_add_symlink_path(
    dir: &str,
    dst: &str,
    dep_type: Option<&str>,
    src: &str,
    instance: Option<&str>,
) -> Result<(String, String), GeneratorError> {
    if dir.is_empty() || dst.is_empty() || src.is_empty() {
        return Err(GeneratorError::InvalidArgument);
    }

    let (dir_prefix, filename) = match src.rfind('/') {
        Some(pos) => {
            let f = &src[pos + 1..];
            if f.is_empty() {
                return Err(GeneratorError::IsDirectory);
            }
            (&src[..pos], f)
        }
        None => ("", src),
    };

    let resolved_name = match instance {
        Some(inst) => {
            if let Some(at_pos) = filename.find("@.") {
                let prefix = &filename[..=at_pos];
                let suffix = &filename[at_pos + 2..];
                format!("{prefix}{inst}.{suffix}")
            } else {
                filename.to_string()
            }
        }
        None => filename.to_string(),
    };

    let from = match dep_type {
        Some(_) if dir_prefix.is_empty() => format!("../{resolved_name}"),
        Some(_) => format!("{dir_prefix}/{resolved_name}"),
        None if dir_prefix.is_empty() => resolved_name.clone(),
        None => format!("{dir_prefix}/{resolved_name}"),
    };

    let to = match dep_type {
        Some(dep) => format!("{dir}/{dst}.{dep}/{resolved_name}"),
        None => format!("{dir}/{dst}"),
    };

    Ok((from, to))
}

/// Mirrors C `generator_add_ordering`.
pub fn generator_ordering_dropin_filename(src: &str, dst: &str) -> String {
    format!("{src}.d/50-order-{dst}.conf")
}

/// Mirrors C `generator_add_ordering`.
pub fn generator_ordering_dropin_content(order: &str, dst: &str, program: &str) -> String {
    format!("{}[Unit]\n{order}={dst}\n", generator_header(program))
}

/// Mirrors C `generator_write_blockdev_dependency`.
pub fn format_blockdev_dependency(what: &str) -> Option<String> {
    if !what.starts_with("/dev/") {
        return None;
    }
    let escaped = unit_name_path_escape(what);
    Some(format!("After=blockdev@{escaped}.target\n"))
}

/// Mirrors C `generator_write_cryptsetup_unit_section()`.
pub fn format_cryptsetup_unit_section(source: Option<&str>) -> String {
    let mut s = String::from(
        "[Unit]\n\
         Description=Cryptography Setup for %I\n\
         Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) \
         man:systemd-cryptsetup@.service(8)\n",
    );
    if let Some(src) = source {
        s.push_str(&format!("SourcePath={src}\n"));
    }
    s.push_str(
        "\n\
         DefaultDependencies=no\n\
         After=cryptsetup-pre.target systemd-udevd-kernel.socket \
         systemd-tpm2-setup-early.service\n\
         Before=blockdev@dev-mapper-%i.target\n\
         Wants=blockdev@dev-mapper-%i.target\n\
         IgnoreOnIsolate=true\n",
    );
    s
}

/// Mirrors C `generator_write_cryptsetup_service_section()`.
pub fn format_cryptsetup_service_section(
    name: &str,
    what: &str,
    key_file: Option<&str>,
    options: Option<&str>,
) -> String {
    let name_e = specifier_escape(name);
    let what_e = specifier_escape(what);
    let key_e = key_file.map(|k| specifier_escape(k));
    let opts_e = options.map(|o| specifier_escape(o));

    format!(
        "\n\
         [Service]\n\
         Type=oneshot\n\
         RemainAfterExit=yes\n\
         TimeoutSec=infinity\n\
         KeyringMode=shared\n\
         OOMScoreAdjust=500\n\
         ImportCredential=cryptsetup.*\n\
         ExecStart=systemd-cryptsetup attach '{name_e}' '{what_e}' '{}' '{}'\n\
         ExecStop=systemd-cryptsetup detach '{name_e}'\n",
        strempty(key_e.as_deref()),
        strempty(opts_e.as_deref()),
    )
}

/// Mirrors C `generator_write_veritysetup_unit_section()`.
pub fn format_veritysetup_unit_section(source: Option<&str>) -> String {
    let mut s = String::from(
        "[Unit]\n\
         Description=Integrity Protection Setup for %I\n\
         Documentation=man:veritytab(5) man:systemd-veritysetup-generator(8) \
         man:systemd-veritysetup@.service(8)\n",
    );
    if let Some(src) = source {
        s.push_str(&format!("SourcePath={src}\n"));
    }
    s.push_str(
        "DefaultDependencies=no\n\
         IgnoreOnIsolate=true\n\
         After=veritysetup-pre.target systemd-udevd-kernel.socket\n\
         Before=blockdev@dev-mapper-%i.target\n\
         Wants=blockdev@dev-mapper-%i.target\n",
    );
    s
}

/// Mirrors C `generator_write_veritysetup_service_section()`.
pub fn format_veritysetup_service_section(
    name: &str,
    data_what: &str,
    hash_what: &str,
    roothash: Option<&str>,
    options: Option<&str>,
) -> String {
    let name_e = specifier_escape(name);
    let data_e = specifier_escape(data_what);
    let hash_e = specifier_escape(hash_what);
    let root_e = roothash.map(|r| specifier_escape(r));
    let opts_e = options.map(|o| specifier_escape(o));

    format!(
        "\n\
         [Service]\n\
         Type=oneshot\n\
         RemainAfterExit=yes\n\
         ExecStart=systemd-veritysetup attach '{name_e}' '{data_e}' '{hash_e}' '{}' '{}'\n\
         ExecStop=systemd-veritysetup detach '{name_e}'\n",
        empty_to_dash(root_e.as_deref()),
        strempty(opts_e.as_deref()),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── generator_header ────────────────────────────────────────────────

    #[test]
    fn test_generator_header() {
        let h = generator_header("systemd-fstab-generator");
        assert!(h.contains("# Automatically generated by systemd-fstab-generator"));
        assert!(h.ends_with("\n\n"));
    }

    #[test]
    fn test_generator_header_empty_program() {
        let h = generator_header("");
        assert_eq!(h, "# Automatically generated by \n\n");
    }

    // ── parse_gpt_auto_root ─────────────────────────────────────────────

    #[test]
    fn test_parse_gpt_auto_root_known_values() {
        assert_eq!(parse_gpt_auto_root("root", "gpt-auto"), GptAutoRoot::On);
        assert_eq!(
            parse_gpt_auto_root("root", "gpt-auto-force"),
            GptAutoRoot::Force
        );
        assert_eq!(parse_gpt_auto_root("root", "dissect"), GptAutoRoot::Dissect);
        assert_eq!(
            parse_gpt_auto_root("root", "dissect-force"),
            GptAutoRoot::DissectForce
        );
    }

    #[test]
    fn test_parse_gpt_auto_root_off_and_unknown() {
        assert_eq!(parse_gpt_auto_root("root", "off"), GptAutoRoot::Off);
        assert_eq!(
            parse_gpt_auto_root("root", "something-else"),
            GptAutoRoot::Off
        );
        assert_eq!(parse_gpt_auto_root("root", "UUID=abc"), GptAutoRoot::Off);
    }

    #[test]
    #[should_panic(expected = "switch_name must not be empty")]
    fn test_parse_gpt_auto_root_empty_switch_panics() {
        parse_gpt_auto_root("", "gpt-auto");
    }

    #[test]
    #[should_panic(expected = "value must not be empty")]
    fn test_parse_gpt_auto_root_empty_value_panics() {
        parse_gpt_auto_root("root", "");
    }

    // ── soft_rebooted_from_value ────────────────────────────────────────

    #[test]
    fn test_soft_rebooted_from_value() {
        assert!(!soft_rebooted_from_value(None));
        assert!(!soft_rebooted_from_value(Some("0")));
        assert!(soft_rebooted_from_value(Some("1")));
        assert!(soft_rebooted_from_value(Some("42")));
        assert!(!soft_rebooted_from_value(Some("notanumber")));
        assert!(!soft_rebooted_from_value(Some("")));
    }

    // ── generator_add_symlink_path ──────────────────────────────────────

    #[test]
    fn test_symlink_path_dependency() {
        let (from, to) = generator_add_symlink_path(
            "/run/systemd/generator",
            "multi-user.target",
            Some("wants"),
            "test.service",
            None,
        )
        .unwrap();
        assert_eq!(from, "../test.service");
        assert_eq!(
            to,
            "/run/systemd/generator/multi-user.target.wants/test.service"
        );
    }

    #[test]
    fn test_symlink_path_alias() {
        let (from, to) = generator_add_symlink_path(
            "/run/systemd/generator",
            "multi-user.target",
            None,
            "test.service",
            None,
        )
        .unwrap();
        assert_eq!(from, "test.service");
        assert_eq!(to, "/run/systemd/generator/multi-user.target");
    }

    #[test]
    fn test_symlink_path_with_absolute_src() {
        let (from, to) = generator_add_symlink_path(
            "/run/generator",
            "local-fs.target",
            Some("requires"),
            "/usr/lib/systemd/system/systemd-fsck-root.service",
            None,
        )
        .unwrap();
        assert_eq!(from, "/usr/lib/systemd/system/systemd-fsck-root.service");
        assert_eq!(
            to,
            "/run/generator/local-fs.target.requires/systemd-fsck-root.service"
        );
    }

    #[test]
    fn test_symlink_path_with_instance() {
        let (from, to) = generator_add_symlink_path(
            "/run/generator",
            "local-fs.target",
            Some("wants"),
            "systemd-fsck@.service",
            Some("dev-sda1"),
        )
        .unwrap();
        assert_eq!(from, "../systemd-fsck@dev-sda1.service");
        assert_eq!(
            to,
            "/run/generator/local-fs.target.wants/systemd-fsck@dev-sda1.service"
        );
    }

    #[test]
    fn test_symlink_path_empty_input_errors() {
        assert_eq!(
            generator_add_symlink_path("", "dst", Some("wants"), "src", None),
            Err(GeneratorError::InvalidArgument)
        );
        assert_eq!(
            generator_add_symlink_path("dir", "", Some("wants"), "src", None),
            Err(GeneratorError::InvalidArgument)
        );
        assert_eq!(
            generator_add_symlink_path("dir", "dst", Some("wants"), "", None),
            Err(GeneratorError::InvalidArgument)
        );
    }

    #[test]
    fn test_symlink_path_directory_errors() {
        assert_eq!(
            generator_add_symlink_path("dir", "dst", Some("wants"), "/path/to/", None),
            Err(GeneratorError::IsDirectory)
        );
    }

    // ── generator_ordering_dropin_* ─────────────────────────────────────

    #[test]
    fn test_ordering_dropin_filename() {
        assert_eq!(
            generator_ordering_dropin_filename("local-fs.target", "systemd-fsck@dev-sda1.service"),
            "local-fs.target.d/50-order-systemd-fsck@dev-sda1.service.conf"
        );
    }

    #[test]
    fn test_ordering_dropin_content() {
        let content = generator_ordering_dropin_content(
            "After",
            "systemd-fsck-root.service",
            "systemd-fstab-generator",
        );
        assert!(content.contains("[Unit]"));
        assert!(content.contains("After=systemd-fsck-root.service"));
        assert!(content.contains("Automatically generated by systemd-fstab-generator"));
    }

    // ── format_blockdev_dependency ──────────────────────────────────────

    #[test]
    fn test_format_blockdev_dependency_device() {
        let line = format_blockdev_dependency("/dev/sda1").unwrap();
        assert_eq!(line, "After=blockdev@dev-sda1.target\n");
    }

    #[test]
    fn test_format_blockdev_dependency_nested() {
        let line = format_blockdev_dependency("/dev/mapper/luks-root").unwrap();
        assert_eq!(line, "After=blockdev@dev-mapper-luks-root.target\n");
    }

    #[test]
    fn test_format_blockdev_dependency_non_device() {
        assert_eq!(format_blockdev_dependency("/sys/class/net"), None);
        assert_eq!(format_blockdev_dependency("LABEL=boot"), None);
    }

    // ── format_cryptsetup_unit_section ──────────────────────────────────

    #[test]
    fn test_cryptsetup_unit_section_without_source() {
        let s = format_cryptsetup_unit_section(None);
        assert!(s.starts_with("[Unit]"));
        assert!(s.contains("Description=Cryptography Setup for %I"));
        assert!(!s.contains("SourcePath="));
        assert!(s.contains("IgnoreOnIsolate=true"));
    }

    #[test]
    fn test_cryptsetup_unit_section_with_source() {
        let s = format_cryptsetup_unit_section(Some("/etc/crypttab"));
        assert!(s.contains("SourcePath=/etc/crypttab"));
    }

    // ── format_cryptsetup_service_section ───────────────────────────────

    #[test]
    fn test_cryptsetup_service_section_basic() {
        let s = format_cryptsetup_service_section("luks-root", "/dev/sda1", None, None);
        assert!(s.contains("[Service]"));
        assert!(s.contains("Type=oneshot"));
        assert!(s.contains("RemainAfterExit=yes"));
        assert!(s.contains("attach 'luks-root' '/dev/sda1' '' ''"));
        assert!(s.contains("detach 'luks-root'"));
    }

    #[test]
    fn test_cryptsetup_service_section_with_all_fields() {
        let s = format_cryptsetup_service_section(
            "luks",
            "/dev/sda1",
            Some("/etc/keys/luks.key"),
            Some("timeout=30s"),
        );
        assert!(s.contains("'/etc/keys/luks.key'"));
        assert!(s.contains("'timeout=30s'"));
    }

    #[test]
    fn test_cryptsetup_service_section_specifier_escaping() {
        let s = format_cryptsetup_service_section("100%luks", "/dev/sda%2", None, None);
        assert!(s.contains("'100%%luks'"));
        assert!(s.contains("'/dev/sda%%2'"));
    }

    // ── format_veritysetup_unit_section ─────────────────────────────────

    #[test]
    fn test_veritysetup_unit_section_without_source() {
        let s = format_veritysetup_unit_section(None);
        assert!(s.starts_with("[Unit]"));
        assert!(s.contains("Description=Integrity Protection Setup for %I"));
        assert!(!s.contains("SourcePath="));
    }

    #[test]
    fn test_veritysetup_unit_section_with_source() {
        let s = format_veritysetup_unit_section(Some("/etc/veritytab"));
        assert!(s.contains("SourcePath=/etc/veritytab"));
        assert!(s.contains("After=veritysetup-pre.target"));
    }

    // ── format_veritysetup_service_section ──────────────────────────────

    #[test]
    fn test_veritysetup_service_section_full() {
        let s = format_veritysetup_service_section(
            "myroot",
            "/dev/sda2",
            "/dev/sda3",
            Some("abc123"),
            Some("ignore-corruption"),
        );
        assert!(s.contains("[Service]"));
        assert!(s.contains("attach 'myroot' '/dev/sda2' '/dev/sda3' 'abc123' 'ignore-corruption'"));
        assert!(s.contains("detach 'myroot'"));
    }

    #[test]
    fn test_veritysetup_service_section_empty_roothash_becomes_dash() {
        let s = format_veritysetup_service_section("test", "/dev/d0", "/dev/d1", Some(""), None);
        assert!(s.contains("'test' '/dev/d0' '/dev/d1' '-' ''"));
    }

    #[test]
    fn test_veritysetup_service_section_none_roothash_becomes_dash() {
        let s = format_veritysetup_service_section("test", "/dev/d0", "/dev/d1", None, None);
        assert!(s.contains("'test' '/dev/d0' '/dev/d1' '-' ''"));
    }

    // ── specifier_escape ────────────────────────────────────────────────

    #[test]
    fn test_specifier_escape() {
        assert_eq!(specifier_escape("hello"), "hello");
        assert_eq!(specifier_escape("100%"), "100%%");
        assert_eq!(specifier_escape("%n%s"), "%%n%%s");
        assert_eq!(specifier_escape(""), "");
    }

    // ── cescape ─────────────────────────────────────────────────────────

    #[test]
    fn test_cescape() {
        assert_eq!(cescape("hello"), "hello");
        assert_eq!(cescape("a\\b"), "a\\\\b");
        assert_eq!(cescape("a'b"), "a\\'b");
        assert_eq!(cescape("a\"b"), "a\\\"b");
        assert_eq!(cescape("a\nb"), "a\\nb");
        assert_eq!(cescape("a\tb"), "a\\tb");
        assert_eq!(cescape("/dev/sda1"), "/dev/sda1");
        assert_eq!(cescape(""), "");
    }

    // ── empty_to_dash / strempty ────────────────────────────────────────

    #[test]
    fn test_empty_to_dash() {
        assert_eq!(empty_to_dash(None), "-");
        assert_eq!(empty_to_dash(Some("")), "-");
        assert_eq!(empty_to_dash(Some("abc")), "abc");
    }

    #[test]
    fn test_strempty() {
        assert_eq!(strempty(None), "");
        assert_eq!(strempty(Some("abc")), "abc");
    }

    // ── unit_name_path_escape ───────────────────────────────────────────

    #[test]
    fn test_unit_name_path_escape() {
        assert_eq!(unit_name_path_escape("/dev/sda1"), "dev-sda1");
        assert_eq!(unit_name_path_escape("/dev/mapper/luks"), "dev-mapper-luks");
        assert_eq!(unit_name_path_escape("/"), "");
        assert_eq!(unit_name_path_escape("///"), "");
        assert_eq!(unit_name_path_escape("/sys"), "sys");
    }
}
