[lib]
path = "lib.rs"

[package]
publish = false
name = "systemd-import"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1-or-later"
description = "Rust port of systemd/src/import/"

[dependencies]
systemd-shared-rs = { path = "../../shared/rust" }
bitflags = "2"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "systemd-importd"
path = "main.rs"
