/* SPDX-License-Identifier: LGPL-2.1-or-later */
/* Shadow test: C virt.h VIRTUALIZATION_IS_VM/CONTAINER vs Rust */

#include <assert.h>

#include "rust/virt.h"
#include "tests.h"
#include "virt.h"

static void test_VIRTUALIZATION_IS_VM(void) {
        assert_se(VIRTUALIZATION_IS_VM(VIRTUALIZATION_NONE) == rs_VIRTUALIZATION_IS_VM(VIRTUALIZATION_NONE));
        assert_se(VIRTUALIZATION_IS_VM(VIRTUALIZATION_KVM) == rs_VIRTUALIZATION_IS_VM(VIRTUALIZATION_KVM));
        assert_se(VIRTUALIZATION_IS_VM(VIRTUALIZATION_QEMU) == rs_VIRTUALIZATION_IS_VM(VIRTUALIZATION_QEMU));
        assert_se(VIRTUALIZATION_IS_VM(VIRTUALIZATION_VM_OTHER) == rs_VIRTUALIZATION_IS_VM(VIRTUALIZATION_VM_OTHER));
        assert_se(VIRTUALIZATION_IS_VM(VIRTUALIZATION_SYSTEMD_NSPAWN) == rs_VIRTUALIZATION_IS_VM(VIRTUALIZATION_SYSTEMD_NSPAWN));
        assert_se(VIRTUALIZATION_IS_VM(VIRTUALIZATION_CONTAINER_OTHER) == rs_VIRTUALIZATION_IS_VM(VIRTUALIZATION_CONTAINER_OTHER));
        assert_se(VIRTUALIZATION_IS_VM(-1) == rs_VIRTUALIZATION_IS_VM(-1));
        assert_se(VIRTUALIZATION_IS_VM(100) == rs_VIRTUALIZATION_IS_VM(100));
}

static void test_VIRTUALIZATION_IS_CONTAINER(void) {
        assert_se(VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_NONE) == rs_VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_NONE));
        assert_se(VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_KVM) == rs_VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_KVM));
        assert_se(VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_SYSTEMD_NSPAWN) == rs_VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_SYSTEMD_NSPAWN));
        assert_se(VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_LXC) == rs_VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_LXC));
        assert_se(VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_DOCKER) == rs_VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_DOCKER));
        assert_se(VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_CONTAINER_OTHER) == rs_VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_CONTAINER_OTHER));
        assert_se(VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_VM_OTHER) == rs_VIRTUALIZATION_IS_CONTAINER(VIRTUALIZATION_VM_OTHER));
        assert_se(VIRTUALIZATION_IS_CONTAINER(-1) == rs_VIRTUALIZATION_IS_CONTAINER(-1));
        assert_se(VIRTUALIZATION_IS_CONTAINER(100) == rs_VIRTUALIZATION_IS_CONTAINER(100));
}

int main(int argc, char **argv) {
        test_VIRTUALIZATION_IS_VM();
        test_VIRTUALIZATION_IS_CONTAINER();
        return 0;
}
