/* SPDX-License-Identifier: LGPL-2.1-or-later */

#include "io-util.h"
#include "tests.h"

TEST(FILE_SIZE_VALID) {
        ASSERT_TRUE(FILE_SIZE_VALID(0));
        ASSERT_TRUE(FILE_SIZE_VALID(1024));
        ASSERT_TRUE(FILE_SIZE_VALID(UINT64_MAX >> 1));
        ASSERT_FALSE(FILE_SIZE_VALID(UINT64_MAX));
}

TEST(FILE_SIZE_VALID_OR_INFINITY) {
        ASSERT_TRUE(FILE_SIZE_VALID_OR_INFINITY(0));
        ASSERT_TRUE(FILE_SIZE_VALID_OR_INFINITY(UINT64_MAX));
        ASSERT_TRUE(FILE_SIZE_VALID_OR_INFINITY(1024));
}

DEFINE_TEST_MAIN(LOG_DEBUG);
