# SPDX-License-Identifier: LGPL-2.1-or-later
# Cargo.toml exists for IDE support (rust-analyzer) only.
# Meson is the authoritative build system — do NOT use `cargo build`.
[package]
publish = false
name = "systemd-hwdb-rs"
version = "0.0.1"
edition = "2024"
[dependencies]
systemd-shared-rs = { path = "../../shared/rust" }
[lib]
crate-type = ["lib"]
name = "systemd_hwdb_rs"
path = "lib.rs"

[[bin]]
name = "systemd-hwdb"
path = "main.rs"
