// SPDX-License-Identifier: LGPL-2.1-or-later
//
// Shadow Rust modules for src/resolve/
#![deny(unsafe_op_in_unsafe_fn)]
#![allow(dead_code)]

pub mod ffi;
#[path = "fuzz-dns-packet.rs"]
pub mod fuzz_dns_packet;
#[path = "fuzz-etc-hosts.rs"]
pub mod fuzz_etc_hosts;
#[path = "fuzz-resource-record.rs"]
pub mod fuzz_resource_record;
pub mod port_sync;
#[path = "resolvconf-compat.rs"]
pub mod resolvconf_compat;
#[path = "resolvectl.rs"]
pub mod resolvectl;
#[path = "resolved.rs"]
pub mod resolved;
#[path = "resolved-bus.rs"]
pub mod resolved_bus;
#[path = "resolved-conf.rs"]
pub mod resolved_conf;
#[path = "resolved-dns-browse-services.rs"]
pub mod resolved_dns_browse_services;
#[path = "resolved-dns-cache.rs"]
pub mod resolved_dns_cache;
#[path = "resolved-dns-delegate.rs"]
pub mod resolved_dns_delegate;
#[path = "resolved-dns-delegate-bus.rs"]
pub mod resolved_dns_delegate_bus;
#[path = "resolved-dns-dnssec.rs"]
pub mod resolved_dns_dnssec;
#[path = "resolved-dns-query.rs"]
pub mod resolved_dns_query;
#[path = "resolved-dns-scope.rs"]
pub mod resolved_dns_scope;
#[path = "resolved-dns-search-domain.rs"]
pub mod resolved_dns_search_domain;
#[path = "resolved-dns-server.rs"]
pub mod resolved_dns_server;
#[path = "resolved-dns-stream.rs"]
pub mod resolved_dns_stream;
#[path = "resolved-dns-stub.rs"]
pub mod resolved_dns_stub;
#[path = "resolved-dns-synthesize.rs"]
pub mod resolved_dns_synthesize;
#[path = "resolved-dns-transaction.rs"]
pub mod resolved_dns_transaction;
#[path = "resolved-dns-trust-anchor.rs"]
pub mod resolved_dns_trust_anchor;
#[path = "resolved-dns-zone.rs"]
pub mod resolved_dns_zone;
#[path = "resolved-dnssd.rs"]
pub mod resolved_dnssd;
#[path = "resolved-dnssd-bus.rs"]
pub mod resolved_dnssd_bus;
#[path = "resolved-dnstls.rs"]
pub mod resolved_dnstls;
#[path = "resolved-etc-hosts.rs"]
pub mod resolved_etc_hosts;
#[path = "resolved-hook.rs"]
pub mod resolved_hook;
#[path = "resolved-link.rs"]
pub mod resolved_link;
#[path = "resolved-link-bus.rs"]
pub mod resolved_link_bus;
#[path = "resolved-llmnr.rs"]
pub mod resolved_llmnr;
#[path = "resolved-manager.rs"]
pub mod resolved_manager;
#[path = "resolved-mdns.rs"]
pub mod resolved_mdns;
#[path = "resolved-resolv-conf.rs"]
pub mod resolved_resolv_conf;
#[path = "resolved-socket-graveyard.rs"]
pub mod resolved_socket_graveyard;
#[path = "resolved-static-records.rs"]
pub mod resolved_static_records;
#[path = "resolved-util.rs"]
pub mod resolved_util;
#[path = "resolved-varlink.rs"]
pub mod resolved_varlink;
#[path = "test-dns-answer.rs"]
pub mod test_dns_answer;
#[path = "test-dns-cache.rs"]
pub mod test_dns_cache;
#[path = "test-dns-packet.rs"]
pub mod test_dns_packet;
#[path = "test-dns-packet-append.rs"]
pub mod test_dns_packet_append;
#[path = "test-dns-packet-extract.rs"]
pub mod test_dns_packet_extract;
#[path = "test-dns-query.rs"]
pub mod test_dns_query;
#[path = "test-dns-question.rs"]
pub mod test_dns_question;
#[path = "test-dns-rr.rs"]
pub mod test_dns_rr;
#[path = "test-dns-search-domain.rs"]
pub mod test_dns_search_domain;
#[path = "test-dns-synthesize.rs"]
pub mod test_dns_synthesize;
#[path = "test-dns-zone.rs"]
pub mod test_dns_zone;
#[path = "test-dnssec.rs"]
pub mod test_dnssec;
#[path = "test-dnssec-complex.rs"]
pub mod test_dnssec_complex;
#[path = "test-resolve-tables.rs"]
pub mod test_resolve_tables;
#[path = "test-resolved-dummy-server.rs"]
pub mod test_resolved_dummy_server;
#[path = "test-resolved-etc-hosts.rs"]
pub mod test_resolved_etc_hosts;
#[path = "test-resolved-link.rs"]
pub mod test_resolved_link;
#[path = "test-resolved-packet.rs"]
pub mod test_resolved_packet;
#[path = "test-resolved-stream.rs"]
pub mod test_resolved_stream;
