[package]
publish = false
name = "systemd-network"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1-or-later"
description = "Rust port of systemd network management"

[lib]
name = "systemd_network"
path = "lib.rs"

[dependencies]
libc = { workspace = true }
nix = { workspace = true }
thiserror = "1.0"
systemd-shared-rs = { path = "../../shared/rust" }
libsystemd-network-rust = { path = "../../libsystemd-network/rust" }
systemd-platform-rs = { path = "../../platform/rust" }
systemd-event-loop-rs = { path = "../../event-loop/rust" }

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "systemd-networkd"
path = "main.rs"
