# SPDX-License-Identifier: LGPL-2.1-or-later
# Cargo.toml exists for IDE support (rust-analyzer) only.
# Meson is the authoritative build system — do NOT use `cargo build`.
[package]
publish = false
name = "systemd-id128-rs"
version = "0.0.1"
edition = "2021"
[dependencies]
systemd-libsystemd-rs = { path = "../../libsystemd/rust" }
libc = "0.2"
[lib]
crate-type = ["lib"]
name = "systemd_id128_rs"
path = "lib.rs"

[[bin]]
name = "systemd-id128"
path = "main.rs"
