// SPDX-License-Identifier: LGPL-2.1-or-later
//
// PORT-SYNC: src/basic/confidential-virt.c, src/basic/confidential-virt.h
//
// Confidential virtualization string table lookups.
//
// Provides the `ConfidentialVirtualization` enum and bidirectional string
// conversion functions that mirror the C `DEFINE_STRING_TABLE_LOOKUP` macro
// expansion for `confidential_virtualization_table[]`.
//
// Skipped: `detect_confidential_virtualization()` (requires CPUID, MSR, and
// filesystem access that is architecture-specific).

// ── Enum ──────────────────────────────────────────────────────────────────

/// Confidential virtualization technology types.
///
/// Mirrors the C enum `ConfidentialVirtualization` from confidential-virt.h:
/// ```c
/// typedef enum ConfidentialVirtualization {
///         CONFIDENTIAL_VIRTUALIZATION_NONE = 0,
///         CONFIDENTIAL_VIRTUALIZATION_SEV,
///         CONFIDENTIAL_VIRTUALIZATION_SEV_ES,
///         CONFIDENTIAL_VIRTUALIZATION_SEV_SNP,
///         CONFIDENTIAL_VIRTUALIZATION_TDX,
///         CONFIDENTIAL_VIRTUALIZATION_PROTVIRT,
///         CONFIDENTIAL_VIRTUALIZATION_CCA,
///         _CONFIDENTIAL_VIRTUALIZATION_MAX,
///         _CONFIDENTIAL_VIRTUALIZATION_INVALID = -EINVAL,
/// } ConfidentialVirtualization;
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ConfidentialVirtualization {
    None = 0,
    Sev = 1,
    SevEs = 2,
    SevSnp = 3,
    Tdx = 4,
    Protvirt = 5,
    Cca = 6,
}

impl ConfidentialVirtualization {
    /// Number of valid variants (matches `_CONFIDENTIAL_VIRTUALIZATION_MAX`).
    pub const MAX: usize = 7;

    /// Sentinel for invalid values (mirrors `_CONFIDENTIAL_VIRTUALIZATION_INVALID = -EINVAL`).
    pub const INVALID: i32 = -22;
}

// ── String table ──────────────────────────────────────────────────────────

static CONFIDENTIAL_VIRT_TABLE: &[(ConfidentialVirtualization, &str)] = &[
    (ConfidentialVirtualization::None, "none"),
    (ConfidentialVirtualization::Sev, "sev"),
    (ConfidentialVirtualization::SevEs, "sev-es"),
    (ConfidentialVirtualization::SevSnp, "sev-snp"),
    (ConfidentialVirtualization::Tdx, "tdx"),
    (ConfidentialVirtualization::Protvirt, "protvirt"),
    (ConfidentialVirtualization::Cca, "cca"),
];

// ── Conversion functions ──────────────────────────────────────────────────

/// Convert a `ConfidentialVirtualization` value to its string representation.
///
/// Mirrors the C `confidential_virtualization_to_string()` generated by
/// `DEFINE_STRING_TABLE_LOOKUP`. Returns `None` for out-of-range indices
/// (the C version returns `NULL`).
pub fn confidential_virtualization_to_string(
    v: ConfidentialVirtualization,
) -> Option<&'static str> {
    CONFIDENTIAL_VIRT_TABLE
        .iter()
        .find(|(variant, _)| *variant == v)
        .map(|(_, s)| *s)
}

/// Parse a string into a `ConfidentialVirtualization` value.
///
/// Mirrors the C `confidential_virtualization_from_string()` generated by
/// `DEFINE_STRING_TABLE_LOOKUP`. Case-sensitive, matching C's `streq()`.
/// Returns `Err(InvalidInput)` for unknown strings.
pub fn confidential_virtualization_from_string(
    s: &str,
) -> Result<ConfidentialVirtualization, InvalidInput> {
    for (variant, name) in CONFIDENTIAL_VIRT_TABLE {
        if *name == s {
            return Ok(*variant);
        }
    }
    Err(InvalidInput)
}

/// Error returned when a string does not map to a known variant.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InvalidInput;

impl std::fmt::Display for InvalidInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "invalid confidential virtualization type")
    }
}

impl std::error::Error for InvalidInput {}

// ── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // -- to_string -------------------------------------------------------------

    #[test]
    fn test_to_string_all_variants() {
        assert_eq!(
            confidential_virtualization_to_string(ConfidentialVirtualization::None),
            Some("none")
        );
        assert_eq!(
            confidential_virtualization_to_string(ConfidentialVirtualization::Sev),
            Some("sev")
        );
        assert_eq!(
            confidential_virtualization_to_string(ConfidentialVirtualization::SevEs),
            Some("sev-es")
        );
        assert_eq!(
            confidential_virtualization_to_string(ConfidentialVirtualization::SevSnp),
            Some("sev-snp")
        );
        assert_eq!(
            confidential_virtualization_to_string(ConfidentialVirtualization::Tdx),
            Some("tdx")
        );
        assert_eq!(
            confidential_virtualization_to_string(ConfidentialVirtualization::Protvirt),
            Some("protvirt")
        );
        assert_eq!(
            confidential_virtualization_to_string(ConfidentialVirtualization::Cca),
            Some("cca")
        );
    }

    // -- from_string -----------------------------------------------------------

    #[test]
    fn test_from_string_all_variants() {
        assert_eq!(
            confidential_virtualization_from_string("none"),
            Ok(ConfidentialVirtualization::None)
        );
        assert_eq!(
            confidential_virtualization_from_string("sev"),
            Ok(ConfidentialVirtualization::Sev)
        );
        assert_eq!(
            confidential_virtualization_from_string("sev-es"),
            Ok(ConfidentialVirtualization::SevEs)
        );
        assert_eq!(
            confidential_virtualization_from_string("sev-snp"),
            Ok(ConfidentialVirtualization::SevSnp)
        );
        assert_eq!(
            confidential_virtualization_from_string("tdx"),
            Ok(ConfidentialVirtualization::Tdx)
        );
        assert_eq!(
            confidential_virtualization_from_string("protvirt"),
            Ok(ConfidentialVirtualization::Protvirt)
        );
        assert_eq!(
            confidential_virtualization_from_string("cca"),
            Ok(ConfidentialVirtualization::Cca)
        );
    }

    #[test]
    fn test_from_string_case_sensitive() {
        // C uses streq() which is case-sensitive
        assert!(confidential_virtualization_from_string("SEV").is_err());
        assert!(confidential_virtualization_from_string("TDX").is_err());
        assert!(confidential_virtualization_from_string("None").is_err());
    }

    #[test]
    fn test_from_string_unknown() {
        assert!(confidential_virtualization_from_string("unknown").is_err());
        assert!(confidential_virtualization_from_string("").is_err());
        assert!(confidential_virtualization_from_string("sev-snp-extra").is_err());
    }

    // -- roundtrip -------------------------------------------------------------

    #[test]
    fn test_roundtrip_all_variants() {
        for (variant, name) in CONFIDENTIAL_VIRT_TABLE {
            let back = confidential_virtualization_from_string(name).unwrap();
            assert_eq!(back, *variant);
        }
    }

    #[test]
    fn test_roundtrip_via_to_string() {
        for (variant, _) in CONFIDENTIAL_VIRT_TABLE {
            let s = confidential_virtualization_to_string(*variant).unwrap();
            let back = confidential_virtualization_from_string(s).unwrap();
            assert_eq!(back, *variant);
        }
    }

    // -- enum properties -------------------------------------------------------

    #[test]
    fn test_discriminants_match_c() {
        assert_eq!(ConfidentialVirtualization::None as i32, 0);
        assert_eq!(ConfidentialVirtualization::Sev as i32, 1);
        assert_eq!(ConfidentialVirtualization::SevEs as i32, 2);
        assert_eq!(ConfidentialVirtualization::SevSnp as i32, 3);
        assert_eq!(ConfidentialVirtualization::Tdx as i32, 4);
        assert_eq!(ConfidentialVirtualization::Protvirt as i32, 5);
        assert_eq!(ConfidentialVirtualization::Cca as i32, 6);
    }

    #[test]
    fn test_max_constant() {
        assert_eq!(ConfidentialVirtualization::MAX, 7);
    }

    #[test]
    fn test_invalid_constant() {
        assert_eq!(ConfidentialVirtualization::INVALID, -22);
    }

    #[test]
    fn test_table_length_matches_variants() {
        assert_eq!(
            CONFIDENTIAL_VIRT_TABLE.len(),
            ConfidentialVirtualization::MAX
        );
    }
}
