// SPDX-License-Identifier: LGPL-2.1-or-later
#![deny(unsafe_op_in_unsafe_fn)]
//
// Binary entry point for systemd-gpt-auto-generator

use systemd_gpt_auto_generator_rs::gpt_auto_generator::{
    MOUNT_GROWFS, MOUNT_RW, Role, classify, mount_point, mount_unit_name, root_options,
};

const VERSION: &str = env!("CARGO_PKG_VERSION");

fn print_help() {
    eprintln!("Usage: systemd-gpt-auto-generator [normal-dir early-dir late-dir]");
    eprintln!();
    eprintln!("  -h --help             Show this help");
    eprintln!("     --version          Show package version");
}

fn read_partition_table() -> Vec<(String, String, u64, u64)> {
    let mut partitions = Vec::new();
    let entries = match std::fs::read_dir("/sys/block") {
        Ok(e) => e,
        Err(_) => return partitions,
    };

    for entry in entries.flatten() {
        let block_name = entry.file_name().to_string_lossy().to_string();
        if !block_name.starts_with("sd")
            && !block_name.starts_with("vd")
            && !block_name.starts_with("nvme")
        {
            continue;
        }

        let parts_dir = std::path::PathBuf::from(format!("/sys/block/{}/", block_name));
        let part_entries = match std::fs::read_dir(&parts_dir) {
            Ok(e) => e,
            Err(_) => continue,
        };

        for part_entry in part_entries.flatten() {
            let part_name = part_entry.file_name().to_string_lossy().to_string();
            if !part_name.starts_with(&block_name) {
                continue;
            }

            let guid_path = format!(
                "/sys/block/{}/{}/partition_type_guid",
                block_name, part_name
            );
            let guid = std::fs::read_to_string(&guid_path)
                .unwrap_or_default()
                .trim()
                .to_string();

            let dev_path = format!("/dev/{}", part_name);
            let size_path = format!("/sys/block/{}/{}/size", block_name, part_name);
            let size: u64 = std::fs::read_to_string(&size_path)
                .ok()
                .and_then(|s| s.trim().parse().ok())
                .unwrap_or(0);

            partitions.push((guid, dev_path, size, 0));
        }
    }
    partitions
}

fn generate_mount_unit(
    output_dir: &std::path::Path,
    role: Role,
    device: &str,
) -> std::io::Result<()> {
    let mp = match mount_point(role) {
        Some(p) => p,
        None => return Ok(()),
    };

    let unit_name = mount_unit_name(mp);
    let unit_path = output_dir.join(&unit_name);

    if let Some(parent) = unit_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let options = root_options(false, MOUNT_RW);

    let content = format!(
        "# Automatically generated by systemd-gpt-auto-generator\n\n\
         [Unit]\n\
         Description=Auto-mount {mp}\n\n\
         [Mount]\n\
         What={device}\n\
         Where={mp}\n\
         Options={options}\n"
    );

    std::fs::write(&unit_path, content)?;
    eprintln!("gpt-auto-generator: created {} for {}", unit_name, device);
    Ok(())
}

fn generate_swap_unit(output_dir: &std::path::Path, device: &str) -> std::io::Result<()> {
    let swap_name = device.replace('/', "-").replace('-', "_");
    let unit_name = format!("{}.swap", swap_name);
    let unit_path = output_dir.join(&unit_name);

    if let Some(parent) = unit_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let content = format!(
        "# Automatically generated by systemd-gpt-auto-generator\n\n\
         [Unit]\n\
         Description=Auto-swap {device}\n\n\
         [Swap]\n\
         What={device}\n"
    );

    std::fs::write(&unit_path, content)?;
    eprintln!("gpt-auto-generator: created {} for {}", unit_name, device);
    Ok(())
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    for arg in &args[1..] {
        match arg.as_str() {
            "-h" | "--help" => {
                print_help();
                return;
            }
            "--version" => {
                eprintln!("systemd-gpt-auto-generator {}", VERSION);
                return;
            }
            _ => {}
        }
    }

    let output_dir = if args.len() >= 2 {
        std::path::PathBuf::from(&args[1])
    } else {
        eprintln!("gpt-auto-generator: expected directory argument, running in dry-run mode");
        return;
    };

    let partitions = read_partition_table();
    if partitions.is_empty() {
        eprintln!("gpt-auto-generator: no GPT partitions found");
        return;
    }

    let mut count = 0usize;
    for (guid, device, _size, _flags) in &partitions {
        let role = classify(guid);
        match role {
            Role::Swap => match generate_swap_unit(&output_dir, device) {
                Ok(()) => count += 1,
                Err(e) => eprintln!("gpt-auto-generator: swap unit failed: {}", e),
            },
            Role::Unknown => {}
            _ => match generate_mount_unit(&output_dir, role, device) {
                Ok(()) => count += 1,
                Err(e) => eprintln!("gpt-auto-generator: mount unit failed: {}", e),
            },
        }
    }
    eprintln!("gpt-auto-generator: generated {} units", count);
}
