// SPDX-License-Identifier: LGPL-2.1-or-later
#![deny(unsafe_op_in_unsafe_fn)]
//
// PORT-SYNC: src/run-generator/run-generator.c
//
// Run generator for kernel command line commands.
//
// Parses systemd.run= kernel command line parameters and generates
// a transient service unit to execute the specified commands at boot.

// ── Constants ─────────────────────────────────────────────────────────────

/// Kernel command line keys parsed by this generator.
pub const CMDLINE_KEY_RUN: &str = "systemd.run";
pub const CMDLINE_KEY_SUCCESS_ACTION: &str = "systemd.run_success_action";
pub const CMDLINE_KEY_FAILURE_ACTION: &str = "systemd.run_failure_action";

/// Service unit file name generated by this generator.
pub const SERVICE_NAME: &str = "kernel-command-line.service";

/// Target unit file name generated by this generator.
pub const TARGET_NAME: &str = "kernel-command-line.target";

/// Default target to redirect.
pub const SPECIAL_DEFAULT_TARGET: &str = "default.target";

// ── Enums ─────────────────────────────────────────────────────────────────

/// Result of the generator run.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GeneratorResult {
    /// Nothing to generate (no commands found).
    NothingToDo,
    /// Successfully generated unit files.
    Generated,
}

// ── Structs ───────────────────────────────────────────────────────────────

/// Parsed kernel command line parameters for the run generator.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct GeneratorParams {
    /// Commands to execute from systemd.run=.
    pub commands: Vec<String>,
    /// Success action override.
    pub success_action: Option<String>,
    /// Failure action override.
    pub failure_action: Option<String>,
}

// ── Error type ────────────────────────────────────────────────────────────

/// Errors from the run generator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GeneratorError {
    /// Failed to write unit file.
    UnitWriteFailed(String),
    /// Failed to create symlink.
    SymlinkFailed(String),
    /// Failed to parse command line.
    CmdlineParseFailed(String),
    /// Specifier escape failure.
    SpecifierEscapeFailed,
}

impl std::fmt::Display for GeneratorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GeneratorError::UnitWriteFailed(msg) => {
                write!(f, "Failed to write unit file: {}", msg)
            }
            GeneratorError::SymlinkFailed(msg) => {
                write!(f, "Failed to create symlink: {}", msg)
            }
            GeneratorError::CmdlineParseFailed(msg) => {
                write!(f, "Failed to parse kernel command line: {}", msg)
            }
            GeneratorError::SpecifierEscapeFailed => {
                write!(f, "Failed to escape specifier characters")
            }
        }
    }
}

impl std::error::Error for GeneratorError {}

// ── Helper functions ──────────────────────────────────────────────────────

/// Parse a single kernel command line item into the generator params.
///
/// Mirrors the C `parse()` function. Returns true if the param was modified.
pub fn parse_cmdline_item(key: &str, value: Option<&str>, params: &mut GeneratorParams) -> bool {
    match key {
        k if k == CMDLINE_KEY_RUN => {
            if let Some(v) = value {
                params.commands.push(v.to_string());
                return true;
            }
            false
        }
        k if k == CMDLINE_KEY_SUCCESS_ACTION => {
            if let Some(v) = value {
                params.success_action = Some(v.to_string());
                return true;
            }
            false
        }
        k if k == CMDLINE_KEY_FAILURE_ACTION => {
            if let Some(v) = value {
                params.failure_action = Some(v.to_string());
                return true;
            }
            false
        }
        _ => false,
    }
}

/// Check if there is anything to generate.
pub fn has_work(params: &GeneratorParams) -> bool {
    !params.commands.is_empty() || params.success_action.is_some()
}

/// Escape specifier characters (%) in a command string.
/// The '%' character is special in systemd unit files.
pub fn specifier_escape(s: &str) -> String {
    s.replace('%', "%%")
}

/// Generate the service unit file content.
///
/// Mirrors the C `generate()` function's file output.
pub fn generate_service_unit(params: &GeneratorParams) -> Result<String, GeneratorError> {
    let mut unit = String::new();

    unit.push_str("[Unit]\n");
    unit.push_str("Description=Command from Kernel Command Line\n");
    unit.push_str("Documentation=man:systemd-run-generator(8)\n");
    unit.push_str("SourcePath=/proc/cmdline\n");

    let success = params.success_action.as_deref().unwrap_or("exit");
    if success != "none" {
        unit.push_str(&format!("SuccessAction={}\n", success));
    }

    let failure = params.failure_action.as_deref().unwrap_or("exit");
    if failure != "none" {
        unit.push_str(&format!("FailureAction={}\n", failure));
    }

    unit.push_str("\n[Service]\n");
    unit.push_str("Type=oneshot\n");
    unit.push_str("StandardOutput=journal+console\n");

    for cmd in &params.commands {
        let escaped = specifier_escape(cmd);
        unit.push_str(&format!("ExecStart={}\n", escaped));
    }

    Ok(unit)
}

/// Generate the target unit file content.
pub fn generate_target_unit() -> String {
    let mut unit = String::new();
    unit.push_str("# Automatically generated by systemd-run-generator\n\n");
    unit.push_str("[Unit]\n");
    unit.push_str("Description=Command from Kernel Command Line\n");
    unit.push_str("Documentation=man:systemd-run-generator(8)\n");
    unit.push_str("SourcePath=/proc/cmdline\n");
    unit.push_str("Requires=kernel-command-line.service\n");
    unit.push_str("After=kernel-command-line.service\n");
    unit
}

// ── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_cmdline_item_run() {
        let mut params = GeneratorParams::default();
        assert!(parse_cmdline_item(
            "systemd.run",
            Some("echo hello"),
            &mut params
        ));
        assert_eq!(params.commands, vec!["echo hello"]);
    }

    #[test]
    fn test_parse_cmdline_item_run_no_value() {
        let mut params = GeneratorParams::default();
        assert!(!parse_cmdline_item("systemd.run", None, &mut params));
        assert!(params.commands.is_empty());
    }

    #[test]
    fn test_parse_cmdline_item_success_action() {
        let mut params = GeneratorParams::default();
        assert!(parse_cmdline_item(
            "systemd.run_success_action",
            Some("reboot"),
            &mut params
        ));
        assert_eq!(params.success_action, Some("reboot".to_string()));
    }

    #[test]
    fn test_parse_cmdline_item_failure_action() {
        let mut params = GeneratorParams::default();
        assert!(parse_cmdline_item(
            "systemd.run_failure_action",
            Some("poweroff"),
            &mut params
        ));
        assert_eq!(params.failure_action, Some("poweroff".to_string()));
    }

    #[test]
    fn test_parse_cmdline_item_unknown() {
        let mut params = GeneratorParams::default();
        assert!(!parse_cmdline_item("quiet", None, &mut params));
    }

    #[test]
    fn test_has_work_empty() {
        let params = GeneratorParams::default();
        assert!(!has_work(&params));
    }

    #[test]
    fn test_has_work_with_commands() {
        let params = GeneratorParams {
            commands: vec!["echo test".to_string()],
            ..Default::default()
        };
        assert!(has_work(&params));
    }

    #[test]
    fn test_has_work_with_success_action() {
        let params = GeneratorParams {
            success_action: Some("reboot".to_string()),
            ..Default::default()
        };
        assert!(has_work(&params));
    }

    #[test]
    fn test_specifier_escape() {
        assert_eq!(specifier_escape("echo %i"), "echo %%i");
        assert_eq!(specifier_escape("no specifiers"), "no specifiers");
        assert_eq!(specifier_escape("%%"), "%%%%");
        assert_eq!(specifier_escape("%n %f"), "%%n %%f");
    }

    #[test]
    fn test_generate_service_unit() {
        let params = GeneratorParams {
            commands: vec!["echo hello".to_string()],
            success_action: None,
            failure_action: None,
        };
        let unit = generate_service_unit(&params).unwrap();
        assert!(unit.contains("[Unit]"));
        assert!(unit.contains("[Service]"));
        assert!(unit.contains("ExecStart=echo hello"));
        assert!(unit.contains("SuccessAction=exit"));
        assert!(unit.contains("Type=oneshot"));
    }

    #[test]
    fn test_generate_service_unit_with_actions() {
        let params = GeneratorParams {
            commands: vec!["echo test".to_string()],
            success_action: Some("reboot".to_string()),
            failure_action: Some("poweroff".to_string()),
        };
        let unit = generate_service_unit(&params).unwrap();
        assert!(unit.contains("SuccessAction=reboot"));
        assert!(unit.contains("FailureAction=poweroff"));
    }

    #[test]
    fn test_generate_service_unit_none_actions() {
        let params = GeneratorParams {
            commands: vec!["echo test".to_string()],
            success_action: Some("none".to_string()),
            failure_action: Some("none".to_string()),
        };
        let unit = generate_service_unit(&params).unwrap();
        assert!(!unit.contains("SuccessAction="));
        assert!(!unit.contains("FailureAction="));
    }

    #[test]
    fn test_generate_service_unit_escapes_specifiers() {
        let params = GeneratorParams {
            commands: vec!["echo %i %n".to_string()],
            ..Default::default()
        };
        let unit = generate_service_unit(&params).unwrap();
        assert!(unit.contains("ExecStart=echo %%i %%n"));
        assert!(!unit.contains("ExecStart=echo %i"));
    }

    #[test]
    fn test_generate_target_unit() {
        let unit = generate_target_unit();
        assert!(unit.contains("[Unit]"));
        assert!(unit.contains("Requires=kernel-command-line.service"));
        assert!(unit.contains("After=kernel-command-line.service"));
    }

    #[test]
    fn test_error_display() {
        let err = GeneratorError::UnitWriteFailed("permission denied".to_string());
        assert!(format!("{}", err).contains("permission denied"));
    }
}
