// SPDX-License-Identifier: LGPL-2.1-or-later
//
// PORT-SYNC: src/run-generator/run-generator.c
//
// Generator that creates transient service units from kernel command line.
//
// Parses `systemd.run=`, `systemd.run_success_action=`, and
// `systemd.run_failure_action=` from the kernel command line and generates
// the corresponding systemd unit files, faithfully mirroring the C
// implementation's parsing and generation logic.

// ── Constants ─────────────────────────────────────────────────────────────

/// Unit file name generated by this generator.
pub const UNIT_NAME: &str = "kernel-command-line.service";

/// Target file name generated by this generator.
pub const TARGET_NAME: &str = "kernel-command-line.target";

/// Default target to redirect.
pub const DEFAULT_TARGET: &str = "default.target";

// ── Error type ────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Errno(pub i32);

impl std::fmt::Display for Errno {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "errno {}", self.0)
    }
}

impl std::error::Error for Errno {}

pub type Result<T> = std::result::Result<T, Errno>;

// ── Generator configuration ──────────────────────────────────────────────

/// Parsed generator arguments from the kernel command line.
/// Corresponds to the static `arg_*` variables in run-generator.c.
#[derive(Debug, Clone, Default)]
pub struct GeneratorConfig {
    /// Commands to run (from `systemd.run=`).
    pub commands: Vec<String>,
    /// Success action (from `systemd.run_success_action=`).
    pub success_action: Option<String>,
    /// Failure action (from `systemd.run_failure_action=`).
    pub failure_action: Option<String>,
}

impl GeneratorConfig {
    pub fn new() -> Self {
        Self::default()
    }

    /// Parse a single kernel command line key-value pair.
    /// Corresponds to the `parse()` callback in run-generator.c.
    pub fn parse_cmdline_pair(&mut self, key: &str, value: Option<&str>) -> Result<()> {
        match key {
            "systemd.run" => {
                if let Some(v) = value {
                    self.commands.push(v.to_string());
                }
            }
            "systemd.run_success_action" => {
                if let Some(v) = value {
                    self.success_action = Some(v.to_string());
                }
            }
            "systemd.run_failure_action" => {
                if let Some(v) = value {
                    self.failure_action = Some(v.to_string());
                }
            }
            _ => {}
        }
        Ok(())
    }

    /// Check whether generation should proceed.
    /// Corresponds to `if (strv_isempty(arg_commands) && !arg_success_action) return 0;`.
    pub fn should_generate(&self) -> bool {
        !self.commands.is_empty() || self.success_action.is_some()
    }
}

// ── Unit file generation ──────────────────────────────────────────────────

/// Generate the content of the service unit file.
/// Corresponds to the `generate()` function's fprintf() calls.
pub fn generate_service_unit(config: &GeneratorConfig) -> String {
    let mut unit = String::new();

    // [Unit] section
    unit.push_str("[Unit]\n");
    unit.push_str("Description=Command from Kernel Command Line\n");
    unit.push_str("Documentation=man:systemd-run-generator(8)\n");
    unit.push_str("SourcePath=/proc/cmdline\n");

    // SuccessAction
    if config.success_action.as_deref() != Some("none") {
        let action = config.success_action.as_deref().unwrap_or("exit");
        unit.push_str(&format!("SuccessAction={}\n", action));
    }

    // FailureAction
    if config.failure_action.as_deref() != Some("none") {
        let action = config.failure_action.as_deref().unwrap_or("exit");
        unit.push_str(&format!("FailureAction={}\n", action));
    }

    // [Service] section
    unit.push_str("\n[Service]\n");
    unit.push_str("Type=oneshot\n");
    unit.push_str("StandardOutput=journal+console\n");

    // ExecStart lines
    for cmd in &config.commands {
        let escaped = specifier_escape(cmd);
        unit.push_str(&format!("ExecStart={}\n", escaped));
    }

    unit
}

/// Generate the content of the target unit file.
/// Corresponds to the `write_string_file()` call for `kernel-command-line.target`.
pub fn generate_target_unit() -> String {
    let mut unit = String::new();
    unit.push_str("# Automatically generated by systemd-run-generator\n\n");
    unit.push_str("[Unit]\n");
    unit.push_str("Description=Command from Kernel Command Line\n");
    unit.push_str("Documentation=man:systemd-run-generator(8)\n");
    unit.push_str("SourcePath=/proc/cmdline\n");
    unit.push_str(&format!("Requires={}\n", UNIT_NAME));
    unit.push_str(&format!("After={}\n", UNIT_NAME));
    unit
}

// ── Specifier escaping ────────────────────────────────────────────────────

/// Escape specifier characters (`%`) in command strings.
/// Corresponds to `specifier_escape()` used for ExecStart values.
pub fn specifier_escape(s: &str) -> String {
    s.replace('%', "%%")
}

// ── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_config_empty() {
        let cfg = GeneratorConfig::new();
        assert!(cfg.commands.is_empty());
        assert!(cfg.success_action.is_none());
        assert!(cfg.failure_action.is_none());
        assert!(!cfg.should_generate());
    }

    #[test]
    fn parse_cmdline_run_command() {
        let mut cfg = GeneratorConfig::new();
        cfg.parse_cmdline_pair("systemd.run", Some("/usr/bin/echo hello"))
            .unwrap();
        assert_eq!(cfg.commands.len(), 1);
        assert_eq!(cfg.commands[0], "/usr/bin/echo hello");
        assert!(cfg.should_generate());
    }

    #[test]
    fn parse_cmdline_run_multiple() {
        let mut cfg = GeneratorConfig::new();
        cfg.parse_cmdline_pair("systemd.run", Some("cmd1")).unwrap();
        cfg.parse_cmdline_pair("systemd.run", Some("cmd2")).unwrap();
        assert_eq!(cfg.commands.len(), 2);
    }

    #[test]
    fn parse_cmdline_run_no_value() {
        let mut cfg = GeneratorConfig::new();
        cfg.parse_cmdline_pair("systemd.run", None).unwrap();
        assert!(cfg.commands.is_empty());
    }

    #[test]
    fn parse_cmdline_success_action() {
        let mut cfg = GeneratorConfig::new();
        cfg.parse_cmdline_pair("systemd.run_success_action", Some("reboot"))
            .unwrap();
        assert_eq!(cfg.success_action.as_deref(), Some("reboot"));
    }

    #[test]
    fn parse_cmdline_failure_action() {
        let mut cfg = GeneratorConfig::new();
        cfg.parse_cmdline_pair("systemd.run_failure_action", Some("poweroff"))
            .unwrap();
        assert_eq!(cfg.failure_action.as_deref(), Some("poweroff"));
    }

    #[test]
    fn parse_cmdline_unknown_key_ignored() {
        let mut cfg = GeneratorConfig::new();
        cfg.parse_cmdline_pair("quiet", None).unwrap();
        assert!(cfg.commands.is_empty());
    }

    #[test]
    fn generate_service_unit_basic() {
        let cfg = GeneratorConfig {
            commands: vec!["/usr/bin/echo hello".into()],
            success_action: None,
            failure_action: None,
        };
        let unit = generate_service_unit(&cfg);
        assert!(unit.contains("[Unit]"));
        assert!(unit.contains("[Service]"));
        assert!(unit.contains("ExecStart=/usr/bin/echo hello"));
        assert!(unit.contains("Type=oneshot"));
        assert!(unit.contains("SuccessAction=exit")); // default
    }

    #[test]
    fn generate_service_unit_with_actions() {
        let cfg = GeneratorConfig {
            commands: vec!["cmd".into()],
            success_action: Some("reboot".into()),
            failure_action: Some("poweroff".into()),
        };
        let unit = generate_service_unit(&cfg);
        assert!(unit.contains("SuccessAction=reboot"));
        assert!(unit.contains("FailureAction=poweroff"));
    }

    #[test]
    fn generate_service_unit_action_none_suppressed() {
        let cfg = GeneratorConfig {
            commands: vec!["cmd".into()],
            success_action: Some("none".into()),
            failure_action: Some("none".into()),
        };
        let unit = generate_service_unit(&cfg);
        assert!(!unit.contains("SuccessAction="));
        assert!(!unit.contains("FailureAction="));
    }

    #[test]
    fn generate_target_unit() {
        let target = generate_target_unit();
        assert!(target.contains("[Unit]"));
        assert!(target.contains(&format!("Requires={}", UNIT_NAME)));
        assert!(target.contains(&format!("After={}", UNIT_NAME)));
    }

    #[test]
    fn specifier_escape_percent() {
        assert_eq!(specifier_escape("100%"), "100%%");
        assert_eq!(specifier_escape("%n %i"), "%%n %%i");
    }

    #[test]
    fn specifier_escape_no_special() {
        assert_eq!(specifier_escape("plain command"), "plain command");
    }

    #[test]
    fn should_generate_with_success_action_only() {
        let cfg = GeneratorConfig {
            commands: vec![],
            success_action: Some("reboot".into()),
            failure_action: None,
        };
        assert!(cfg.should_generate());
    }
}
