#!/usr/bin/env python3
"""Statically audit the multi-source Rust string-table C ABI.

This deliberately does not compile or run the port. It verifies the source-level
invariants that previously allowed the header to advertise 137 symbols without
exporting any of them from the Rust static library. It also compares every
declared C signature with the Rust export generated by a macro or written by
hand, and rejects duplicate declarations and implementations.
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "src/shared/rust/netdev_str_tables.h"
FACADE = ROOT / "src/basic/rust/netdev_str_tables.rs"
CORE = ROOT / "src/basic/rust/netdev_str_tables/core.rs"
DOMAIN_DIR = CORE.parent
LEGACY_DUPLICATE = ROOT / "src/shared/rust/netdev_str_tables.rs"


Signature = tuple[tuple[str, ...], str]


def symbols(text: str) -> list[str]:
    return re.findall(r"\brs_[A-Za-z0-9_]+(?=\s*\()", text)


def compact_rust_type(type_name: str) -> str:
    return re.sub(r"\s+", "", type_name)


def c_type(type_name: str) -> str:
    normalized = re.sub(r"\s+", " ", type_name.strip())
    types = {
        "bool": "bool",
        "char *": "*mutc_char",
        "char **": "*mut*mutc_char",
        "const char *": "*constc_char",
        "int": "i32",
        "uint32_t": "u32",
        "uint64_t *": "*mutu64",
        "unsigned short": "u16",
    }
    try:
        return types[normalized]
    except KeyError as error:
        raise ValueError(f"unsupported C type: {normalized}") from error


def c_parameter_type(parameter: str) -> str:
    parameter = re.sub(r"\s+", " ", parameter.strip())
    match = re.fullmatch(
        r"(const char \*|char \*\*|char \*|uint64_t \*|uint32_t|unsigned short|int|bool)"
        r"\s*[A-Za-z_][A-Za-z0-9_]*",
        parameter,
    )
    if not match:
        raise ValueError(f"cannot parse C parameter: {parameter}")
    return c_type(match.group(1))


def header_signatures(header: str) -> list[tuple[str, Signature]]:
    declarations: list[tuple[str, Signature]] = []
    prototype = re.compile(
        r"\b(const\s+char\s*\*|char\s*\*|int|bool)\s*"
        r"(rs_[A-Za-z0-9_]+)\s*\(([^;]*)\)\s*;"
    )
    for match in prototype.finditer(header):
        result, name, parameters = match.groups()
        args = ()
        if parameters.strip() and parameters.strip() != "void":
            args = tuple(c_parameter_type(item) for item in parameters.split(","))
        declarations.append((name, (args, c_type(result))))
    return declarations


def manual_signatures(source: str) -> list[tuple[str, Signature]]:
    exports: list[tuple[str, Signature]] = []
    function = re.compile(
        r"#\[unsafe\(no_mangle\)\][ \t]*\n"
        r"(?:(?:[ \t]*///[^\n]*\n)|(?:[ \t]*\n))*"
        r"pub\s+(?:unsafe\s+)?extern\s+\"C\"\s+fn\s+"
        r"(rs_[A-Za-z0-9_]+)\s*\((.*?)\)"
        r"\s*(?:->\s*([^{]+?))?\s*\{",
        flags=re.DOTALL,
    )
    for match in function.finditer(source):
        name, parameters, result = match.groups()
        args: list[str] = []
        if parameters.strip():
            for parameter in parameters.split(","):
                if not parameter.strip():
                    continue
                if ":" not in parameter:
                    raise ValueError(f"cannot parse Rust parameter for {name}: {parameter}")
                _, type_name = parameter.rsplit(":", 1)
                args.append(compact_rust_type(type_name))
        exports.append((name, (tuple(args), compact_rust_type(result or "()"))))
    return exports


def macro_signatures(source: str) -> list[tuple[str, Signature]]:
    exports: list[tuple[str, Signature]] = []
    invocation = re.compile(
        r"\b(string_table|string_table_boolean|string_table_fallback)!\s*\((.*?)\)\s*;",
        flags=re.DOTALL,
    )
    for match in invocation.finditer(source):
        macro, body = match.groups()
        names = re.findall(r"\brs_[A-Za-z0-9_]+\b", body)
        if len(names) != 2:
            raise ValueError(
                f"{macro}! must define exactly two rs_ exports; found {len(names)} in {body!r}"
            )
        to_name, from_name = names
        if macro == "string_table_fallback":
            exports.append((to_name, (("i32", "*mut*mutc_char"), "i32")))
        else:
            exports.append((to_name, (("i32",), "*constc_char")))
        exports.append((from_name, (("*constc_char",), "i32")))
    return exports


def duplicates(names: list[str]) -> list[str]:
    return sorted(name for name, count in Counter(names).items() if count > 1)


def format_signature(signature: Signature) -> str:
    parameters, result = signature
    return f"({', '.join(parameters)}) -> {result}"


def main() -> int:
    header = HEADER.read_text()
    facade = FACADE.read_text()
    domain_sources = [
        path
        for path in sorted(DOMAIN_DIR.glob("*.rs"))
        if path.name not in {"core.rs", "tests.rs"}
    ]
    source = "\n".join([facade, *(path.read_text() for path in domain_sources)])
    core = CORE.read_text()

    try:
        declarations = header_signatures(header)
        manual = manual_signatures(source)
        generated = macro_signatures(source)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1

    header_symbol_inventory = symbols(header)
    parsed_header_names = [name for name, _ in declarations]
    if header_symbol_inventory != parsed_header_names:
        unparsed = sorted(Counter(header_symbol_inventory) - Counter(parsed_header_names))
        print("unparsed header declarations:", ", ".join(unparsed), file=sys.stderr)
        return 1

    duplicate_declarations = duplicates(parsed_header_names)
    if duplicate_declarations:
        print(
            "duplicate header declarations:", ", ".join(duplicate_declarations), file=sys.stderr
        )
        return 1

    exports = [*manual, *generated]
    duplicate_exports = duplicates([name for name, _ in exports])
    if duplicate_exports:
        print("duplicate Rust exports:", ", ".join(duplicate_exports), file=sys.stderr)
        return 1

    macro_exports = {"string_table", "string_table_boolean", "string_table_fallback"}
    for macro in macro_exports:
        match = re.search(
            rf"macro_rules! {macro} \{{(.*?)^\}}",
            facade,
            flags=re.MULTILINE | re.DOTALL,
        )
        if not match or "#[unsafe(no_mangle)]" not in match.group(1) or 'extern "C"' not in match.group(1):
            print(f"{macro} is not an explicit exported C ABI facade", file=sys.stderr)
            return 1

    declared = dict(declarations)
    implemented = dict(exports)
    missing = sorted(declared.keys() - implemented.keys())
    if missing:
        print("header symbols without an audited export:", ", ".join(missing), file=sys.stderr)
        return 1

    unexpected = sorted(implemented.keys() - declared.keys())
    if unexpected:
        print("Rust exports missing from the ABI header:", ", ".join(unexpected), file=sys.stderr)
        return 1

    mismatches = [
        (name, declared[name], implemented[name])
        for name in declared
        if declared[name] != implemented[name]
    ]
    if mismatches:
        for name, expected, actual in mismatches:
            print(
                f"signature mismatch for {name}: C {format_signature(expected)}, "
                f"Rust {format_signature(actual)}",
                file=sys.stderr,
            )
        return 1

    if "CStr::from_ptr" not in core or "no_mangle" in core:
        print("safe core must own C-string borrowing and must not export ABI symbols", file=sys.stderr)
        return 1

    if LEGACY_DUPLICATE.exists():
        print(f"duplicate unconsumed prototype still exists: {LEGACY_DUPLICATE}", file=sys.stderr)
        return 1

    print(
        f"string-table ABI inventory: declared={len(declared)} exported={len(implemented)} "
        f"manual={len(manual)} macro={len(generated)} signatures={len(declared)} duplicates=0"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
