#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""Inventory the configured C unit-file directive table and Rust parser arms.

The input must be the C file generated by gperf in a configured Meson build.
It intentionally does not parse the Jinja source template: conditional entries
in that template are not an authority for a particular build profile.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
RUST_PARSER = ROOT / "src/core/rust/runtime_manager/unit_file.rs"
BUILD_OPTIONS = Path("meson-info/intro-buildoptions.json")
SETTING = re.compile(
    r'\{\s*"(?P<name>[A-Za-z][A-Za-z0-9]*\.[A-Za-z][A-Za-z0-9]*)"\s*,'
    r'\s*(?P<callback>[A-Za-z_][A-Za-z0-9_]*)\s*,\s*(?P<ltype>[^,]+),'
)
RUST_ARM = re.compile(
    r'\("(?P<section>[a-z]+)",\s*(?P<keys>(?:"[A-Za-z][A-Za-z0-9]*"\s*(?:\|\s*)?)+)\)'
)
KEY = re.compile(r'"([A-Za-z][A-Za-z0-9]*)"')


def fail(message: str) -> None:
    raise ValueError(message)


def profile(build_dir: Path) -> dict[str, object]:
    options_path = build_dir / BUILD_OPTIONS
    if not options_path.is_file():
        fail(f"Meson profile metadata is missing: {options_path}")
    try:
        options = json.loads(options_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        fail(f"cannot parse {options_path}: {error}")
    if not isinstance(options, list):
        fail(f"unexpected Meson option metadata in {options_path}")

    values = {
        entry["name"]: entry.get("value")
        for entry in options
        if isinstance(entry, dict) and isinstance(entry.get("name"), str)
    }
    encoded = json.dumps(values, sort_keys=True, separators=(",", ":")).encode()
    return {
        "build_options": values,
        "fingerprint": hashlib.sha256(encoded).hexdigest(),
    }


def git_revision() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
    ).strip()


def parse_c_table(path: Path, profile_fingerprint: str) -> list[dict[str, object]]:
    if not path.is_file():
        fail(f"generated gperf C authority is missing: {path}")
    rows: list[dict[str, object]] = []
    seen: set[tuple[str, str]] = set()
    for match in SETTING.finditer(path.read_text(encoding="utf-8", errors="strict")):
        section, key = match.group("name").split(".", 1)
        identity = (section.lower(), key)
        if identity in seen:
            fail(f"duplicate C directive in generated table: {section}.{key}")
        seen.add(identity)
        rows.append(
            {
                "section": section.lower(),
                "key": key,
                "unit_type": section.lower(),
                "callback": match.group("callback"),
                "ltype": match.group("ltype").strip(),
                "feature_predicate": f"enabled-in-profile:{profile_fingerprint}",
                "aliases": [],
            }
        )
    if not rows:
        fail(f"no directive rows found in generated authority: {path}")
    return sorted(rows, key=lambda row: (str(row["section"]), str(row["key"])))


def parse_rust_arms(path: Path) -> set[tuple[str, str]]:
    if not path.is_file():
        fail(f"Rust parser is missing: {path}")
    arms: set[tuple[str, str]] = set()
    for match in RUST_ARM.finditer(path.read_text(encoding="utf-8")):
        section = match.group("section")
        arms.update((section, key) for key in KEY.findall(match.group("keys")))
    return arms


def inventory(generated_gperf: Path, meson_build: Path) -> dict[str, object]:
    meson_profile = profile(meson_build)
    c_rows = parse_c_table(generated_gperf, str(meson_profile["fingerprint"]))
    rust_arms = parse_rust_arms(RUST_PARSER)
    c_keys = {(str(row["section"]), str(row["key"])) for row in c_rows}
    rows = []
    for row in c_rows:
        identity = (str(row["section"]), str(row["key"]))
        row = dict(row)
        # This inventory cannot prove a runtime consumer. Be conservative until
        # a later semantic plan records one explicitly.
        row["rust_status"] = (
            "recognized-but-unconsumed" if identity in rust_arms else "not-present"
        )
        row["consumer"] = None
        row["test_classification"] = "unreviewed"
        rows.append(row)

    unmatched_rust = sorted(
        {f"{section}.{key}" for section, key in rust_arms - c_keys}
    )
    return {
        "schema_version": 1,
        "source_commit": git_revision(),
        "generated_gperf": str(generated_gperf.resolve()),
        "meson_profile": meson_profile,
        "rows": rows,
        "unmatched_rust_directives": unmatched_rust,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generated-gperf", type=Path, required=True)
    parser.add_argument("--meson-build", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--allow-unmatched-rust",
        action="store_true",
        help="report Rust-only parser arms without treating them as an inventory error",
    )
    args = parser.parse_args()
    try:
        result = inventory(args.generated_gperf, args.meson_build)
        if result["unmatched_rust_directives"] and not args.allow_unmatched_rust:
            fail(
                "Rust parser directives absent from generated C profile: "
                + ", ".join(result["unmatched_rust_directives"])
            )
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f"unit-directive-inventory: {error}", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"unit-directive-inventory: rows={len(result['rows'])} profile={result['meson_profile']['fingerprint']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
