# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|fedora
Distribution=|centos

[Content]
PrepareScripts=%D/mkosi/mkosi.images/build/mkosi.conf.d/centos-fedora/mkosi.prepare
Packages=
        cargo # Distro package builds use --auto-features enabled and may compile Rust shadows.
        clang-tools-extra
        python3-mypy
        rpm-build
        libasan
        libubsan
        liburing-devel
        compiler-rt
