# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=fedora

[Content]
Packages=
        cargo # Distro package builds use --auto-features enabled and may compile Rust shadows.
        gh
        lcov
        libgcrypt-devel
        libgpg-error-devel
        musl-libc
        musl-clang
        musl-gcc
        ruff
        coccinelle
        shellcheck
