# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=opensuse

[Content]
PrepareScripts=%D/mkosi/mkosi.images/build/mkosi.conf.d/opensuse/mkosi.prepare
Packages=
        cargo # Distro package builds use --auto-features enabled and may compile Rust shadows.
        clang-tools
        coccinelle
        gh
        lcov
        libtss2-tcti-device0
        liburing-devel
        mypy
        python3-ruff
        rpm-build
        ShellCheck
        sysuser-tools
