// SPDX-License-Identifier: LGPL-2.1-or-later
#![deny(unsafe_op_in_unsafe_fn)]
//
// Binary entry point for systemd-fstab-generator (standalone, without external crates)

use std::fs::{self, File};
use std::io::{self, Write};
use std::path::Path;

const FSTAB_PATH: &str = "/etc/fstab";
const VERSION: &str = env!("CARGO_PKG_VERSION");

const EARLY_MOUNTS: &[&str] = &["/", "/usr", "/boot"];

#[derive(Debug, Clone)]
struct Entry {
    what: String,
    where_: String,
    fstype: String,
    options: String,
}

fn print_help() {
    eprintln!("Usage: systemd-fstab-generator [normal-dir early-dir late-dir]");
    eprintln!("\n  -h --help             Show this help");
    eprintln!("     --version          Show package version");
}

fn is_early_mount(where_: &str) -> bool {
    EARLY_MOUNTS.contains(&where_)
}

fn is_network_fs(fstype: &str) -> bool {
    matches!(fstype, "nfs" | "nfs4" | "cifs" | "smbfs")
}

fn unit_name_from_path(where_: &str, ext: &str) -> String {
    if where_ == "/" {
        return format!("-.{}", ext.trim_start_matches('.'));
    }
    let mut name = where_.replace('/', "-");
    if name.starts_with('-') {
        name = name.trim_start_matches('-').to_string();
    }
    name.push_str(ext);
    name
}

fn write_unit_file(path: &Path, content: &str) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut f = File::create(path)?;
    f.write_all(content.as_bytes())?;
    Ok(())
}

fn write_header(content: &mut String) {
    // SPDX header as a comment in INI file is harmless
    content.push_str("# SPDX-License-Identifier: LGPL-2.1-or-later\n");
    content.push_str("# Automatically generated by systemd-fstab-generator\n\n");
}

fn generate_mount_unit(entry: &Entry, output_dir: &Path) -> io::Result<()> {
    let unit_name = unit_name_from_path(&entry.where_, ".mount");
    let unit_path = output_dir.join(&unit_name);

    // Normalize options and inject network-related options if needed
    let mut options = entry.options.clone();
    let mut need_netdev = false;
    if is_network_fs(&entry.fstype) {
        need_netdev = true;
    }
    if options.contains("_netdev") {
        need_netdev = false; // already present
    }
    if need_netdev {
        if options.is_empty() || options == "defaults" {
            options = "_netdev".to_string();
        } else {
            options = format!("{},_netdev", options);
        }
    }

    let mut content = String::new();
    write_header(&mut content);
    content.push_str("[Unit]\n");
    content.push_str(&format!("Description=Mount {}\n", entry.where_));
    if is_network_fs(&entry.fstype) {
        content.push_str("After=network.target\n");
    }
    if entry.options.contains("nofail") || entry.options.contains("fail") {
        content.push_str("OnFailure=success.target\n");
    }
    content.push_str("\n[Mount]\n");
    content.push_str(&format!("What={}\n", entry.what));
    if !entry.fstype.is_empty() && entry.fstype != "auto" {
        content.push_str(&format!("Type={}\n", entry.fstype));
    }
    if !options.is_empty() && options != "defaults" {
        content.push_str(&format!("Options={}\n", options));
    }
    // Basic install target
    content.push_str("\n[Install]\n");
    content.push_str("WantedBy=local-fs.target\n");

    write_unit_file(&unit_path, &content)?;
    eprintln!("fstab-generator: wrote {}", unit_path.display());

    // Automount unit (if requested)
    if entry.options.contains("x-systemd.automount")
        || entry.options.contains("comment=systemd.automount")
    {
        let am_unit_name = unit_name.replace(".mount", ".automount");
        let am_path = output_dir.join(&am_unit_name);
        let mut am_content = String::new();
        write_header(&mut am_content);
        am_content.push_str("[Unit]\n");
        am_content.push_str(&format!("Description=Automount {}\n", entry.where_));
        am_content.push_str("\n[Automount]\n");
        am_content.push_str(&format!("Where={}\n", entry.where_));
        am_content.push_str("TimeoutIdleSec=120\n");
        am_content.push_str("\n[Install]\n");
        am_content.push_str("WantedBy=multi-user.target\n");

        if let Some(parent) = am_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&am_path, am_content)?;
        eprintln!("fstab-generator: wrote {}", am_path.display());
    }

    Ok(())
}

fn generate_swap_unit(entry: &Entry, output_dir: &Path) -> io::Result<()> {
    // Build a swap unit name from the 'what' field
    let swap_name = entry.what.replace('/', "-").replace('-', "_");
    let unit_name = format!("{}.swap", swap_name);
    let unit_path = output_dir.join(&unit_name);

    let mut content = String::new();
    write_header(&mut content);
    content.push_str("[Unit]\n");
    content.push_str(&format!("Description=Swap {}\n", entry.what));
    content.push_str("\n[Swap]\n");
    content.push_str(&format!("What={}\n", entry.what));
    if !entry.options.is_empty() && entry.options != "defaults" {
        content.push_str(&format!("Options={}\n", entry.options));
    }
    content.push_str("\n[Install]\n");
    content.push_str("WantedBy=multi-user.target\n");

    if let Some(parent) = unit_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&unit_path, content)?;
    eprintln!("fstab-generator: wrote {}", unit_path.display());
    Ok(())
}

fn parse_line(line: &str) -> Option<Entry> {
    let s = line.trim();
    if s.is_empty() || s.starts_with('#') {
        return None;
    }
    let parts: Vec<&str> = s.split_whitespace().collect();
    if parts.len() < 6 {
        // Invalid line
        return None;
    }
    Some(Entry {
        what: parts[0].to_string(),
        where_: parts[1].to_string(),
        fstype: parts[2].to_string(),
        options: parts[3].to_string(),
    })
}

fn main() {
    // Minimal Linux-specific implementation; keep isolated
    if cfg!(not(target_os = "linux")) {
        eprintln!(
            "systemd-fstab-generator is only supported on Linux in this simplified implementation."
        );
        return;
    }

    let args: Vec<String> = std::env::args().collect();
    for arg in &args[1..] {
        if arg == "-h" || arg == "--help" {
            print_help();
            return;
        }
        if arg == "--version" {
            eprintln!("systemd-fstab-generator {}", VERSION);
            return;
        }
    }

    // Dry-run mode when fewer than 4 args (program + 3 dirs)
    if args.len() < 4 {
        eprintln!("fstab-generator: running in dry-run mode (syntax check only)");
        if !Path::new(FSTAB_PATH).exists() {
            eprintln!(
                "fstab-generator: {} not found, skipping syntax check",
                FSTAB_PATH
            );
            return;
        }
        match fs::read_to_string(FSTAB_PATH) {
            Ok(content) => {
                for line in content.lines() {
                    let _ = parse_line(line);
                }
            }
            Err(e) => {
                eprintln!("fstab-generator: cannot read {}: {}", FSTAB_PATH, e);
            }
        }
        return;
    }

    // Expect 3 positional directories: normal_dir, early_dir, late_dir
    let normal_dir = &args[1];
    let early_dir = &args[2];
    let late_dir = &args[3];

    // Ensure output dirs exist
    let normal_out = Path::new(normal_dir);
    let early_out = Path::new(early_dir);
    let late_out = Path::new(late_dir);
    if let Err(e) = fs::create_dir_all(normal_out) {
        eprintln!("fstab-generator: cannot create dir {}: {}", normal_dir, e);
        return;
    }
    if let Err(e) = fs::create_dir_all(early_out) {
        eprintln!("fstab-generator: cannot create dir {}: {}", early_dir, e);
        return;
    }
    if let Err(e) = fs::create_dir_all(late_out) {
        eprintln!("fstab-generator: cannot create dir {}: {}", late_dir, e);
        return;
    }

    // Read fstab and generate units
    let fstab_content = match fs::read_to_string(FSTAB_PATH) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("fstab-generator: cannot read {}: {}", FSTAB_PATH, e);
            return;
        }
    };

    for line in fstab_content.lines() {
        if let Some(entry) = parse_line(line) {
            // Determine destination dir
            let is_swap = entry.fstype == "swap";
            if is_swap {
                let dir = Path::new(normal_dir);
                if let Err(e) = generate_swap_unit(&entry, dir) {
                    eprintln!("fstab-generator: error writing swap unit: {}", e);
                }
                continue;
            }

            let out_dir = if is_early_mount(&entry.where_) {
                early_out
            } else if is_network_fs(&entry.fstype) {
                late_out
            } else {
                normal_out
            };
            if let Err(e) = generate_mount_unit(&entry, out_dir) {
                eprintln!("fstab-generator: error writing mount unit: {}", e);
            }
        }
    }

    eprintln!("fstab-generator: done");
}
