// SPDX-License-Identifier: LGPL-2.1-or-later
//
// Shadow Rust modules for src/udev/

#![allow(dead_code)]
#![deny(unsafe_op_in_unsafe_fn)]

pub mod ffi;
#[path = "ata_id/ata_id.rs"]
pub mod ata_id_ata_id;
#[path = "cdrom_id/cdrom_id.rs"]
pub mod cdrom_id_cdrom_id;
#[path = "dmi_memory_id/dmi_memory_id.rs"]
pub mod dmi_memory_id_dmi_memory_id;
#[path = "fido_id/fido_id.rs"]
pub mod fido_id_fido_id;
#[path = "fido_id/fido_id_desc.rs"]
pub mod fido_id_fido_id_desc;
#[path = "fido_id/fuzz-fido-id-desc.rs"]
pub mod fido_id_fuzz_fido_id_desc;
#[path = "fido_id/test-fido-id-desc.rs"]
pub mod fido_id_test_fido_id_desc;
#[path = "fuzz-udev-rule-parse-value.rs"]
pub mod fuzz_udev_rule_parse_value;
#[path = "fuzz-udev-rules.rs"]
pub mod fuzz_udev_rules;
#[path = "iocost/iocost.rs"]
pub mod iocost_iocost;
#[path = "mtd_probe/mtd_probe.rs"]
pub mod mtd_probe_mtd_probe;
#[path = "mtd_probe/probe_smartmedia.rs"]
pub mod mtd_probe_probe_smartmedia;
#[path = "net/fuzz-link-parser.rs"]
pub mod net_fuzz_link_parser;
#[path = "net/link-config.rs"]
pub mod net_link_config;
#[path = "net/test-link-config-tables.rs"]
pub mod net_test_link_config_tables;
#[path = "scsi_id/scsi_id.rs"]
pub mod scsi_id_scsi_id;
#[path = "scsi_id/scsi_serial.rs"]
pub mod scsi_id_scsi_serial;
#[path = "test-udev-builtin.rs"]
pub mod test_udev_builtin;
#[path = "test-udev-format.rs"]
pub mod test_udev_format;
#[path = "test-udev-manager.rs"]
pub mod test_udev_manager;
#[path = "test-udev-node.rs"]
pub mod test_udev_node;
#[path = "test-udev-rule-runner.rs"]
pub mod test_udev_rule_runner;
#[path = "test-udev-rules.rs"]
pub mod test_udev_rules;
#[path = "test-udev-spawn.rs"]
pub mod test_udev_spawn;
#[path = "udev-builtin-blkid.rs"]
pub mod udev_builtin_blkid;
#[path = "udev-builtin-btrfs.rs"]
pub mod udev_builtin_btrfs;
#[path = "udev-builtin-dissect_image.rs"]
pub mod udev_builtin_dissect_image;
#[path = "udev-builtin-factory_reset.rs"]
pub mod udev_builtin_factory_reset;
#[path = "udev-builtin-hwdb.rs"]
pub mod udev_builtin_hwdb;
#[path = "udev-builtin-input_id.rs"]
pub mod udev_builtin_input_id;
#[path = "udev-builtin-keyboard.rs"]
pub mod udev_builtin_keyboard;
#[path = "udev-builtin-kmod.rs"]
pub mod udev_builtin_kmod;
#[path = "udev-builtin-net_driver.rs"]
pub mod udev_builtin_net_driver;
#[path = "udev-builtin-net_id.rs"]
pub mod udev_builtin_net_id;
#[path = "udev-builtin-net_setup_link.rs"]
pub mod udev_builtin_net_setup_link;
#[path = "udev-builtin-path_id.rs"]
pub mod udev_builtin_path_id;
#[path = "udev-builtin-tpm2_id.rs"]
pub mod udev_builtin_tpm2_id;
#[path = "udev-builtin-uaccess.rs"]
pub mod udev_builtin_uaccess;
#[path = "udev-builtin-usb_id.rs"]
pub mod udev_builtin_usb_id;
#[path = "udev-builtin.rs"]
pub mod udev_builtin;
#[path = "udev-db-monitor.rs"]
pub mod udev_db_monitor;
#[path = "udev-config.rs"]
pub mod udev_config;
#[path = "udev-ctrl.rs"]
pub mod udev_ctrl;
#[path = "udev-dump.rs"]
pub mod udev_dump;
#[path = "udev-error.rs"]
pub mod udev_error;
#[path = "udev-event.rs"]
pub mod udev_event;
#[path = "udev-format.rs"]
pub mod udev_format;
#[path = "udev-manager-ctrl.rs"]
pub mod udev_manager_ctrl;
#[path = "udev-manager.rs"]
pub mod udev_manager;
#[path = "udev-node.rs"]
pub mod udev_node;
#[path = "udev-rules.rs"]
pub mod udev_rules;
#[path = "udev-rule-engine.rs"]
pub mod udev_rule_engine;
#[path = "udev-spawn.rs"]
pub mod udev_spawn;
#[path = "udev-varlink.rs"]
pub mod udev_varlink;
#[path = "udev-watch.rs"]
pub mod udev_watch;
#[path = "udev-worker.rs"]
pub mod udev_worker;
#[path = "uevent-netlink.rs"]
pub mod uevent_netlink;
#[path = "udevadm-cat.rs"]
pub mod udevadm_cat;
#[path = "udevadm-control.rs"]
pub mod udevadm_control;
#[path = "udevadm-hwdb.rs"]
pub mod udevadm_hwdb;
#[path = "udevadm-info.rs"]
pub mod udevadm_info;
#[path = "udevadm-lock.rs"]
pub mod udevadm_lock;
#[path = "udevadm-monitor.rs"]
pub mod udevadm_monitor;
#[path = "udevadm-settle.rs"]
pub mod udevadm_settle;
#[path = "udevadm-test-builtin.rs"]
pub mod udevadm_test_builtin;
#[path = "udevadm-test.rs"]
pub mod udevadm_test;
#[path = "udevadm-trigger.rs"]
pub mod udevadm_trigger;
#[path = "udevadm-util.rs"]
pub mod udevadm_util;
#[path = "udevadm-verify.rs"]
pub mod udevadm_verify;
#[path = "udevadm-wait.rs"]
pub mod udevadm_wait;
#[path = "udevadm.rs"]
pub mod udevadm;
#[path = "udevd.rs"]
pub mod udevd;
#[path = "v4l_id/v4l_id.rs"]
pub mod v4l_id_v4l_id;
