[package]
publish = false
name = "systemd-login"
version = "0.1.0"
edition = "2024"
license = "LGPL-2.1-or-later"
description = "Rust port of systemd/src/login/"

[lib]
path = "lib.rs"

[dependencies]
systemd-shared-rs = { path = "../../shared/rust" }
bitflags = { workspace = true }
systemd-platform-rs = { path = "../../platform/rust" }
systemd-event-loop-rs = { path = "../../event-loop/rust" }

[[bin]]
name = "systemd-logind"
path = "main.rs"
